### ISSUE TITLE
AssertionError with some genes

### ISSUE THREAD

**Issue by oyvindbusk** [brentp/seqcover#21]
Nice tool! I have noticed some genes (e.g. HNRNPA1) gives an assertionerror, and I have not been able to figure out why. 

code used:
```sh
./seqcover report --genes HNRNPA1 \
--fasta $fasta samples/*_recal.per-base.d4 \
--background seqcover_out/seqcover_p5.d4 \
-r my_genes_report.html \
--hg19

# Gives:
fatal.nim(49)            sysFatal
Error: unhandled exception: transcript.nim(143, 14) `r_off - l_off == o_exon[1] - o_exon[0]`  [AssertionError]
```

**Comment by brentp** [comment]
thanks for reporting. I'll look into this.

**Comment by brentp** [comment]
I have fixed this in master. Here is an executable with the recent changes if you want to try. Thanks for reporting!
[seqcover.gz](https://github.com/brentp/seqcover/files/5410705/seqcover.gz)

**Comment by oyvindbusk** [comment]
Perfect, thanks!
