### ISSUE TITLE
Invalid integer exception

### ISSUE THREAD

**Issue by jaspez** [brentp/seqcover#28]
Hi everyone,

I've been testing `seqcover` tool with one sample coverage file processed by `mosdepth` in *.bed.gz format. This sample is from a WES experiment. I run the next command and it gave me an error:

`${seqcover} report --genes BRCA1 --fasta ${fasta} ${input}/sample.bed.gz -r ${outfile} --hg19
`
> [seqcover] read 1 sample coverage files
17	41195811	41277881
strutils.nim(1087)       parseInt
Error: unhandled exception: invalid integer: CEX-chr17-41196311-41197870 [ValueError]

It looks for BRCA1 coordinates on my BED file but shows this exception error. I don't know if there is a problem with the name of regions. Ask for any other information you need.

I hope you could help me, thanks in advance.

**Comment by brentp** [comment]
Hi, you should send the per-base.bed.gz file from `mosdepth` to `seqcover` looks like you are trying to use the `regions.bed.gz` or similar. The `per-base.bed.gz` will have only 4 columns.

**Comment by jaspez** [comment]
Thanks Brent, it worked fine now.

I would like to ask when will the next release be available. I'm interested in the new offline mode with `save-transcripts` command, it is already in the README but not available on the current v0.0.3 binary file.

**Comment by brentp** [comment]
Hi, I tagged a new release: https://github.com/brentp/seqcover/releases/tag/v0.0.4
hope that helps. Let me know any more questions.

**Comment by jaspez** [comment]
Thank you so much for your help!
