### ISSUE TITLE
Error: --hg19 coordinates

### ISSUE THREAD

**Issue by oyvindbusk** [brentp/seqcover#31]
Hi, 

Not sure I got this right, but... I am using seqcover with the --hg19-flag. Suddenly I get an error with specific genes. 

CTDP1 is an example.

`./seqcover report --genes CTDP1 --hg19 --fasta ${fasta} -r my_genes_report.html ${d4}
`
reports the following error:
`Error: unhandled exception: d4:error seeking to position: 18:79679792 [ValueError]`

I think the problem is that CTDP1 is on the fringe of exon 18, and when I get the coordinates in GRCh38 (for some reason), it has some parts that are outside the hg19-genome. 

When I make seqcover print the `gene.transcripts` object from the get_genes proc, they are identical regardless of the --hg19-flag. 

This is more likely something to do with the response from mygene.info, but I wanted to report it here in case somebody else is seeing the same error, or if it is something I am doing wrong.

**Comment by brentp** [comment]
thanks for flagging this. would be good to verify that the coordinates are requested correctly (from seqcover) and what exactly is returned from mygene.

**Comment by brwnj** [comment]
You've likely already glanced at the return from mygene, but here's the JSON for CTDP1 (id:9150): https://mygene.info/v3/gene/9150?fields=name,symbol,exons,exons_hg19

**Comment by oyvindbusk** [comment]
The guys at mygene.info are looking into it. 

https://github.com/biothings/mygene.info/issues/118#issuecomment-957755310

**Comment by oyvindbusk** [comment]
The problem was due to some upstream data change in mygene.info. It's fixed now, so I'm closing this issue.

**Comment by brentp** [comment]
excellent! thanks for following up.
